const TooltipActionTypes = {
  SET_ACTIVE: "SET_ACTIVE",
  SET_INACTIVE: "SET_INACTIVE",

  START_ACTIVE_TIMER: "START_ACTIVE_TIMER",
  CANCEL_ACTIVE_TIMER: "CANCEL_ACTIVE_TIMER",

  START_INACTIVE_TIMER: "START_INACTIVE_TIMER",
  CANCEL_INACTIVE_TIMER: "CANCEL_INACTIVE_TIMER"
};

export default TooltipActionTypes;
