const EnquiryPageActionTypes = {
  ENQUIRY_PAGE_SET_VISITED: "ENQUIRY_PAGE_SET_VISITED",
  ENQUIRY_PAGE_SET_VALID: "ENQUIRY_PAGE_SET_VALID",
  ENQUIRY_PAGE_SET_INVALID: "ENQUIRY_PAGE_SET_INVALID",
  ENQUIRY_PAGE_NEXT: "ENQUIRY_PAGE_NEXT",
  ENQUIRY_PAGE_PREV: "ENQUIRY_PAGE_PREV"
};

export default EnquiryPageActionTypes;
